import { z } from "zod";
import { editableModelPricing } from "./models";
import { Scenario } from "./types";

const now = () => new Date().toISOString();

export const scenarioSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  currency: z.enum(["EUR", "USD", "GBP"]).default("EUR"),
  monthlyVisitors: z.number().nonnegative(),
  signupConversionRate: z.number().nonnegative(),
  freeToPaidConversionRate: z.number().nonnegative(),
  paidUsers: z.number().nonnegative(),
  freeUsers: z.number().nonnegative(),
  monthlyChurnRate: z.number().nonnegative(),
  averagePricePerMonth: z.number().nonnegative(),
  targetMRR: z.number().nonnegative(),
  targetARR: z.number().nonnegative(),
  fixedMonthlyCosts: z.number().nonnegative(),
  variableCostPerPaidUser: z.number().nonnegative(),
  variableCostPerFreeUser: z.number().nonnegative(),
  paymentFeePercent: z.number().nonnegative(),
  paymentFeeFixed: z.number().nonnegative(),
  aiFeatures: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
      enabled: z.boolean(),
      modelName: z.string(),
      inputTokensPerCall: z.number().nonnegative(),
      outputTokensPerCall: z.number().nonnegative(),
      callsPerFreeUserPerMonth: z.number().nonnegative(),
      callsPerPaidUserPerMonth: z.number().nonnegative(),
      inputCostPerMillionTokens: z.number().nonnegative(),
      outputCostPerMillionTokens: z.number().nonnegative(),
    }),
  ),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const scenariosSchema = z.array(scenarioSchema);

export function scenarioTemplates(): Scenario[] {
  const cheap = editableModelPricing[3];
  const premium = editableModelPricing[4];
  const date = now();
  const base = {
    currency: "EUR" as const,
    monthlyVisitors: 5000,
    signupConversionRate: 6,
    freeToPaidConversionRate: 10,
    paidUsers: 50,
    freeUsers: 400,
    monthlyChurnRate: 4,
    averagePricePerMonth: 39,
    targetMRR: 6000,
    targetARR: 120000,
    fixedMonthlyCosts: 450,
    variableCostPerPaidUser: 2,
    variableCostPerFreeUser: 0.1,
    paymentFeePercent: 2.9,
    paymentFeeFixed: 0.3,
    aiFeatures: [],
    createdAt: date,
    updatedAt: date,
  };
  const ai = (
    id: string,
    name: string,
    callsPerFreeUserPerMonth: number,
    callsPerPaidUserPerMonth: number,
    model: (typeof editableModelPricing)[number] = cheap,
  ) => ({
    id,
    name,
    enabled: true,
    modelName: model.name,
    inputTokensPerCall: model.name.includes("premium") ? 1800 : 1100,
    outputTokensPerCall: model.name.includes("premium") ? 1200 : 650,
    callsPerFreeUserPerMonth,
    callsPerPaidUserPerMonth,
    inputCostPerMillionTokens: model.inputCostPerMillionTokens,
    outputCostPerMillionTokens: model.outputCostPerMillionTokens,
  });

  return [
    {
      id: "template-solo-bootstrapped",
      name: "Solo Bootstrapped B2B",
      description: "A small paid-first SaaS with simple infrastructure and no freemium burden.",
      currency: "EUR",
      monthlyVisitors: 2500,
      signupConversionRate: 5,
      freeToPaidConversionRate: 18,
      paidUsers: 35,
      freeUsers: 120,
      monthlyChurnRate: 2.5,
      averagePricePerMonth: 49,
      targetMRR: 4000,
      targetARR: 75000,
      fixedMonthlyCosts: 220,
      variableCostPerPaidUser: 1.8,
      variableCostPerFreeUser: 0.05,
      paymentFeePercent: 2.9,
      paymentFeeFixed: 0.3,
      aiFeatures: [],
      createdAt: date,
      updatedAt: date,
    },
    {
      id: "template-ai-prosumer",
      name: "AI Prosumer Tool",
      description: "Usage-heavy AI product with a low monthly price and tighter margin pressure.",
      currency: "EUR",
      monthlyVisitors: 12000,
      signupConversionRate: 9,
      freeToPaidConversionRate: 6,
      paidUsers: 70,
      freeUsers: 950,
      monthlyChurnRate: 6,
      averagePricePerMonth: 24,
      targetMRR: 8000,
      targetARR: 150000,
      fixedMonthlyCosts: 640,
      variableCostPerPaidUser: 1.2,
      variableCostPerFreeUser: 0.12,
      paymentFeePercent: 2.9,
      paymentFeeFixed: 0.3,
      aiFeatures: [
        {
          id: "template-ai-prosumer-feature",
          name: "AI workspace assistant",
          enabled: true,
          modelName: premium.name,
          inputTokensPerCall: 1800,
          outputTokensPerCall: 1100,
          callsPerFreeUserPerMonth: 6,
          callsPerPaidUserPerMonth: 90,
          inputCostPerMillionTokens: premium.inputCostPerMillionTokens,
          outputCostPerMillionTokens: premium.outputCostPerMillionTokens,
        },
      ],
      createdAt: date,
      updatedAt: date,
    },
    {
      id: "template-productized-service",
      name: "Productized Service SaaS",
      description: "Higher-touch B2B product with stronger pricing and moderate operating costs.",
      currency: "EUR",
      monthlyVisitors: 1800,
      signupConversionRate: 4,
      freeToPaidConversionRate: 22,
      paidUsers: 24,
      freeUsers: 80,
      monthlyChurnRate: 2,
      averagePricePerMonth: 149,
      targetMRR: 10000,
      targetARR: 180000,
      fixedMonthlyCosts: 900,
      variableCostPerPaidUser: 9,
      variableCostPerFreeUser: 0.25,
      paymentFeePercent: 2.9,
      paymentFeeFixed: 0.3,
      aiFeatures: [
        {
          id: "template-service-feature",
          name: "Internal delivery automation",
          enabled: true,
          modelName: cheap.name,
          inputTokensPerCall: 1400,
          outputTokensPerCall: 650,
          callsPerFreeUserPerMonth: 0,
          callsPerPaidUserPerMonth: 45,
          inputCostPerMillionTokens: cheap.inputCostPerMillionTokens,
          outputCostPerMillionTokens: cheap.outputCostPerMillionTokens,
        },
      ],
      createdAt: date,
      updatedAt: date,
    },
    {
      ...base,
      id: "template-trust-maa",
      name: "Trust MAA Compliance Monitor",
      description: "Trust-center and marketing-claims assistant for agencies that need lightweight compliance evidence.",
      monthlyVisitors: 4200,
      signupConversionRate: 6.5,
      freeToPaidConversionRate: 12,
      paidUsers: 58,
      freeUsers: 310,
      monthlyChurnRate: 3.2,
      averagePricePerMonth: 59,
      targetMRR: 8500,
      targetARR: 160000,
      fixedMonthlyCosts: 520,
      variableCostPerPaidUser: 3.4,
      variableCostPerFreeUser: 0.12,
      aiFeatures: [ai("template-trust-maa-feature", "Evidence review assistant", 2, 35)],
    },
    {
      ...base,
      id: "template-review-radar",
      name: "Review Radar for Local Services",
      description: "Review monitoring and reply drafting for dentists, salons, clinics, and local professional services.",
      monthlyVisitors: 8000,
      signupConversionRate: 8,
      freeToPaidConversionRate: 7,
      paidUsers: 62,
      freeUsers: 700,
      monthlyChurnRate: 4.5,
      averagePricePerMonth: 29,
      targetMRR: 6000,
      targetARR: 100000,
      fixedMonthlyCosts: 380,
      variableCostPerPaidUser: 1.5,
      variableCostPerFreeUser: 0.08,
      aiFeatures: [ai("template-review-radar-feature", "Reply draft generator", 4, 50)],
    },
    {
      ...base,
      id: "template-invoice-chaser",
      name: "Invoice Chaser for Freelancers",
      description: "Simple accounts receivable tracker with automated reminder schedules for solo operators.",
      monthlyVisitors: 11000,
      signupConversionRate: 10,
      freeToPaidConversionRate: 4,
      paidUsers: 45,
      freeUsers: 1000,
      monthlyChurnRate: 5.5,
      averagePricePerMonth: 12,
      targetMRR: 3000,
      targetARR: 50000,
      fixedMonthlyCosts: 180,
      variableCostPerPaidUser: 0.7,
      variableCostPerFreeUser: 0.03,
    },
    {
      ...base,
      id: "template-churn-notes",
      name: "Churn Notes for Indie SaaS",
      description: "Cancellation feedback tagging and retention experiments for small subscription products.",
      monthlyVisitors: 3600,
      signupConversionRate: 5,
      freeToPaidConversionRate: 16,
      paidUsers: 48,
      freeUsers: 210,
      monthlyChurnRate: 3.8,
      averagePricePerMonth: 45,
      targetMRR: 5000,
      targetARR: 90000,
      fixedMonthlyCosts: 320,
      variableCostPerPaidUser: 1.6,
      variableCostPerFreeUser: 0.04,
      aiFeatures: [ai("template-churn-notes-feature", "Cancellation insight summarizer", 1, 20)],
    },
    {
      ...base,
      id: "template-policy-pulse",
      name: "Policy Pulse for HR Teams",
      description: "Internal policy update tracker for remote teams that need lightweight employee acknowledgements.",
      monthlyVisitors: 2200,
      signupConversionRate: 4.5,
      freeToPaidConversionRate: 20,
      paidUsers: 32,
      freeUsers: 90,
      monthlyChurnRate: 2.2,
      averagePricePerMonth: 99,
      targetMRR: 9000,
      targetARR: 180000,
      fixedMonthlyCosts: 760,
      variableCostPerPaidUser: 6.5,
      variableCostPerFreeUser: 0.12,
      aiFeatures: [ai("template-policy-pulse-feature", "Policy diff explainer", 0, 30)],
    },
    {
      ...base,
      id: "template-founder-crm",
      name: "Founder CRM Lite",
      description: "Tiny CRM for founders tracking warm intros, investors, early customers, and follow-ups.",
      monthlyVisitors: 6500,
      signupConversionRate: 9,
      freeToPaidConversionRate: 5.5,
      paidUsers: 50,
      freeUsers: 560,
      monthlyChurnRate: 6,
      averagePricePerMonth: 15,
      targetMRR: 4000,
      targetARR: 70000,
      fixedMonthlyCosts: 260,
      variableCostPerPaidUser: 0.9,
      variableCostPerFreeUser: 0.04,
    },
    {
      ...base,
      id: "template-meeting-minutes",
      name: "Meeting Minutes for Consultants",
      description: "Client-call notes, action items, and follow-up summaries for boutique consulting teams.",
      monthlyVisitors: 7000,
      signupConversionRate: 7.5,
      freeToPaidConversionRate: 8,
      paidUsers: 70,
      freeUsers: 480,
      monthlyChurnRate: 4,
      averagePricePerMonth: 35,
      targetMRR: 7500,
      targetARR: 130000,
      fixedMonthlyCosts: 520,
      variableCostPerPaidUser: 2.8,
      variableCostPerFreeUser: 0.09,
      aiFeatures: [ai("template-meeting-minutes-feature", "Call summary generator", 3, 70, premium)],
    },
    {
      ...base,
      id: "template-vendor-renewals",
      name: "Vendor Renewal Tracker",
      description: "Renewal calendar and spend warnings for small companies with too many SaaS subscriptions.",
      monthlyVisitors: 3000,
      signupConversionRate: 6,
      freeToPaidConversionRate: 15,
      paidUsers: 42,
      freeUsers: 170,
      monthlyChurnRate: 2.8,
      averagePricePerMonth: 79,
      targetMRR: 9000,
      targetARR: 170000,
      fixedMonthlyCosts: 480,
      variableCostPerPaidUser: 2.1,
      variableCostPerFreeUser: 0.05,
    },
    {
      ...base,
      id: "template-landing-ab",
      name: "Landing Page Test Bench",
      description: "Micro A/B testing dashboard for founders validating positioning before writing code.",
      monthlyVisitors: 15000,
      signupConversionRate: 12,
      freeToPaidConversionRate: 2.8,
      paidUsers: 52,
      freeUsers: 1700,
      monthlyChurnRate: 7,
      averagePricePerMonth: 19,
      targetMRR: 5000,
      targetARR: 90000,
      fixedMonthlyCosts: 300,
      variableCostPerPaidUser: 1,
      variableCostPerFreeUser: 0.05,
    },
    {
      ...base,
      id: "template-support-tagger",
      name: "Support Ticket Tagger",
      description: "AI-assisted ticket classification and trend summaries for small B2B support teams.",
      monthlyVisitors: 5200,
      signupConversionRate: 6,
      freeToPaidConversionRate: 11,
      paidUsers: 64,
      freeUsers: 360,
      monthlyChurnRate: 3.5,
      averagePricePerMonth: 69,
      targetMRR: 9000,
      targetARR: 160000,
      fixedMonthlyCosts: 680,
      variableCostPerPaidUser: 4.5,
      variableCostPerFreeUser: 0.1,
      aiFeatures: [ai("template-support-tagger-feature", "Ticket classifier and summary", 2, 80)],
    },
  ];
}

export function demoScenarios(): Scenario[] {
  const cheap = editableModelPricing[3];
  const premium = editableModelPricing[4];
  const date = now();

  return [
    {
      id: "demo-lean-b2b",
      name: "Lean B2B Micro-SaaS",
      description: "Focused paid product with modest traffic, high intent, and controlled costs.",
      currency: "EUR",
      monthlyVisitors: 6000,
      signupConversionRate: 7,
      freeToPaidConversionRate: 14,
      paidUsers: 72,
      freeUsers: 360,
      monthlyChurnRate: 3,
      averagePricePerMonth: 39,
      targetMRR: 5000,
      targetARR: 100000,
      fixedMonthlyCosts: 420,
      variableCostPerPaidUser: 2.2,
      variableCostPerFreeUser: 0.15,
      paymentFeePercent: 2.9,
      paymentFeeFixed: 0.3,
      aiFeatures: [
        {
          id: "demo-b2b-ai",
          name: "AI onboarding helper",
          enabled: true,
          modelName: cheap.name,
          inputTokensPerCall: 900,
          outputTokensPerCall: 500,
          callsPerFreeUserPerMonth: 3,
          callsPerPaidUserPerMonth: 25,
          inputCostPerMillionTokens: cheap.inputCostPerMillionTokens,
          outputCostPerMillionTokens: cheap.outputCostPerMillionTokens,
        },
      ],
      createdAt: date,
      updatedAt: date,
    },
    {
      id: "demo-ai-heavy",
      name: "AI-heavy Freemium SaaS",
      description: "Large free audience, premium model usage, and pricing pressure.",
      currency: "EUR",
      monthlyVisitors: 25000,
      signupConversionRate: 11,
      freeToPaidConversionRate: 3.5,
      paidUsers: 96,
      freeUsers: 2600,
      monthlyChurnRate: 8,
      averagePricePerMonth: 19,
      targetMRR: 10000,
      targetARR: 250000,
      fixedMonthlyCosts: 1150,
      variableCostPerPaidUser: 1.7,
      variableCostPerFreeUser: 0.22,
      paymentFeePercent: 2.9,
      paymentFeeFixed: 0.3,
      aiFeatures: [
        {
          id: "demo-heavy-ai",
          name: "Long-form AI generation",
          enabled: true,
          modelName: premium.name,
          inputTokensPerCall: 2400,
          outputTokensPerCall: 1800,
          callsPerFreeUserPerMonth: 8,
          callsPerPaidUserPerMonth: 140,
          inputCostPerMillionTokens: premium.inputCostPerMillionTokens,
          outputCostPerMillionTokens: premium.outputCostPerMillionTokens,
        },
      ],
      createdAt: date,
      updatedAt: date,
    },
    ...scenarioTemplates().map((scenario) => ({
      ...scenario,
      id: scenario.id.replace("template-", "demo-"),
      createdAt: date,
      updatedAt: date,
      aiFeatures: scenario.aiFeatures.map((feature) => ({
        ...feature,
        id: feature.id.replace("template-", "demo-"),
      })),
    })),
  ];
}

export function duplicateScenario(scenario: Scenario): Scenario {
  const date = now();

  return {
    ...scenario,
    id: crypto.randomUUID(),
    name: `${scenario.name} copy`,
    createdAt: date,
    updatedAt: date,
    aiFeatures: scenario.aiFeatures.map((feature) => ({
      ...feature,
      id: crypto.randomUUID(),
    })),
  };
}

export function scenarioFromTemplate(template: Scenario): Scenario {
  const date = now();

  return {
    ...template,
    id: crypto.randomUUID(),
    createdAt: date,
    updatedAt: date,
    aiFeatures: template.aiFeatures.map((feature) => ({
      ...feature,
      id: crypto.randomUUID(),
    })),
  };
}
